[package]
name = "text-to-emoji"
version = "0.1.0"
authors = ["Mark Pokhil <vfhr.afr@gmail.com>"]
edition = "2018"

[profile.release]
panic = 'abort'
opt-level = 3

[[bin]]
name = "tte"
path = "./src/main.rs"

[dependencies]
clipboard = "0.5.0"
argh = "0.1.6"
