[package]
name = "monketext"
version = "2.2.7"
authors = ["Mark Pokhil <vfhr.afr@gmail.com>"]
edition = "2018"

[[bin]]
name = "mot"
path = "./src/main.rs"

[dependencies]
clipboard = "0.5.0"
argh = "0.1.4"
